### PR TITLE
Release/0.11.0

### LINKED ISSUE #80: Support custom scalaTag (e.g _2.11, _2.12, _2.13) instead of _?
Hey I might have a hacky solution for a complex problem this plugin doesn't compose well with the play plugin. 

So we have a project like 
```
root
-- app (play plugin)
-- api (needs crossbuilding) 
```
But because i need to tag the dependencies as _? then the app sub project tells me hey i cannot resolve this dependency with _?. Because your plugin doesn't apply to the old play plugin. 

So i simple solution would be to set the archive.appendixPattern  to _2.11 and be done with it. But then the plugin complains that it cannot resolve the _2.11 for a 2.12 build.

So currently i resolved it by doing: 
```
compile "com.company:commons-lib_2.11:${commonGrpcVersion}"
crossBuildV211CompileOnly "com.company:commons-lib_2.11:${commonGrpcVersion}"
 crossBuildV212CompileOnly "com.company:commons-lib_2.12:${commonGrpcVersion}"
```

But if this 'feature' was supported the i could just change a project to a cross compiled lib by just applying the plugin and no need to switch dependencies to the dependency with _? notation.

I tried play-framework but that disabled the tests for some weird reason (and it is out of the scope of this ticket)

### LINKED ISSUE #82: Add scala to plugin name
based on discussion in #79 plugin name should include `scala` :)

### LINKED ISSUE #89: Support mixing cross built modules with plain modules in a multi module projects
Forked from #80 discussion

### LINKED ISSUE #90: Should be sufficient to have root module containing scala lib to inference the default Scala version for the project
Extracted from discussion in PR #87 

```
Caused by: java.util.NoSuchElementException: Cannot access first() element from an empty Iterable
	at com.github.prokod.gradle.crossbuild.CrossBuildPlugin$_globDependencyTranslationForMainSourceSetsConfigurations_closure9$_closure16.doCall(CrossBuildPlugin.groovy:149)
	at com.github.prokod.gradle.crossbuild.CrossBuildPlugin$_globDependencyTranslationForMainSourceSetsConfigurations_closure9.doCall(CrossBuildPlugin.groovy:113)
	at com.github.prokod.gradle.crossbuild.CrossBuildPlugin.globDependencyTranslationForMainSourceSetsConfigurations(CrossBuildPlugin.groovy:102)
	at com.github.prokod.gradle.crossbuild.CrossBuildPlugin$_apply_closure3.doCall(CrossBuildPlugin.groovy:63)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingClosure$1.lambda$run$0(DefaultListenerBuildOperationDecorator.java:180)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:60)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingClosure$1.run(DefaultListenerBuildOperationDecorator.java:177)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingClosure.doCall(DefaultListenerBuildOperationDecorator.java:174)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:41)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:231)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:150)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:325)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:235)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:141)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy29.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate$1.execute(LifecycleProjectEvaluator.java:186)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate$1.execute(LifecycleProjectEvaluator.java:183)
	at org.gradle.api.internal.project.DefaultProject.stepEvaluationListener(DefaultProject.java:1446)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate.run(LifecycleProjectEvaluator.java:192)
```

Oke i can tell you the cause

this gives the error (pseudo code)
```
project("A"){
 apply plugin  "crossbuil"
 compile `scalaLib:2.11.12`
}

project("B"){

 apply plugin "crossbuil"
  compile project("A")
}
```

works fine:
```
project("A"){
 apply plugin  "crossbuil"
 compile `scalaLib:2.11.12`
}

project("B"){

 apply plugin "crossbuil"
  compile project("A")
 compile `scalaLib:2.11.12`
}
```

### PR DESCRIPTION
**Pull request by prokod**
This PR prepares release 0.11.0

closes #90, closes #89 , closes #82

### CODE REVIEW

**Comment by prokod** [comment]
Hi @borissmidt lmk please if there are any issues with the staged version as described in #81 .

**Comment by borissmidt** [comment]
Hey sorry i didn't have much time last week i tried out the new plugin version but i get an error:
```
Caused by: java.util.NoSuchElementException: Cannot access first() element from an empty Iterable
	at com.github.prokod.gradle.crossbuild.CrossBuildPlugin$_globDependencyTranslationForMainSourceSetsConfigurations_closure9$_closure16.doCall(CrossBuildPlugin.groovy:149)
	at com.github.prokod.gradle.crossbuild.CrossBuildPlugin$_globDependencyTranslationForMainSourceSetsConfigurations_closure9.doCall(CrossBuildPlugin.groovy:113)
	at com.github.prokod.gradle.crossbuild.CrossBuildPlugin.globDependencyTranslationForMainSourceSetsConfigurations(CrossBuildPlugin.groovy:102)
	at com.github.prokod.gradle.crossbuild.CrossBuildPlugin$_apply_closure3.doCall(CrossBuildPlugin.groovy:63)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingClosure$1.lambda$run$0(DefaultListenerBuildOperationDecorator.java:180)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:60)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingClosure$1.run(DefaultListenerBuildOperationDecorator.java:177)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingClosure.doCall(DefaultListenerBuildOperationDecorator.java:174)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:41)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:231)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:150)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:325)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:235)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:141)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy29.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate$1.execute(LifecycleProjectEvaluator.java:186)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate$1.execute(LifecycleProjectEvaluator.java:183)
	at org.gradle.api.internal.project.DefaultProject.stepEvaluationListener(DefaultProject.java:1446)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate.run(LifecycleProjectEvaluator.java:192)
```

Oke i can tell you the cause

this gives the error (pseudo code)
```
project("A"){
 apply plugin  "crossbuil"
 compile `scalaLib:2.11.12`
}

project("B"){

 apply plugin "crossbuil"
  compile project("A")
}

```

works fine:
```
project("A"){
 apply plugin  "crossbuil"
 compile `scalaLib:2.11.12`
}

project("B"){

 apply plugin "crossbuil"
  compile project("A")
 compile `scalaLib:2.11.12`
}

```

**Comment by prokod** [comment]
Hi @borissmidt thx for the valuable feedback. I will put this as a test and make it compatible with previous version behavior (probably re-enable default Scala version inference which I have inhibited while doing this release). Funny thing I have quite a few tests to check multi-module cases and I didn't trip that, even though I am deliberately not adding scala lib dependency in the module/s that already depends on ones that include the default scala lib dependency :)

**Comment by prokod** [comment]
@borissmidt Hi :)
I was trying to simulate the issue with a test but I could not reproduce. Any other specifics in your case that are not reflected in the pseudo code ?

Cheers

**Comment by borissmidt** [comment]
Not that i know of, it's a bit annoying that its business code and i can
not share the project.

**Comment by borissmidt** [comment]
Maybe if it has 2 indirections to a project?

**Comment by borissmidt** [comment]
I haven't found the cause yet but i found some very good hints with the print logging

```
error COMPILE [DefaultProjectDependency{dependencyProject='project ':http-server', configuration='default'}, DefaultProjectDependency{dependencyProject='project ':rest-client'', configuration='default'}, DefaultProjectDependency{dependencyProject='project ':rest-token-authenticator'', configuration='default'}, DefaultExternalModuleDependency{group='com.company', name='checks-java', version='1.0.4', configuration='default'}, DefaultExternalModuleDependency{group='com.google.protobuf', name='protobuf-java', version='3.6.1', configuration='default'}, DefaultExternalModuleDependency{group='com.thesamet.scalapb', name='scalapb-runtime-grpc_?', version='0.8.2', configuration='default'},[source set 'cross build v211', source set 'cross build v212', source set 'main', source set 'test'] project ':my-project-api'
```
`
println("error ${viewType} ${mainConfig.allDependencies} ${extension.crossBuildSourceSets.container} ${extension.project}") 
`

in method `globDependencyTranslationForMainSourceSetsConfigurations` so it seems to me that the plugin doesn't look recursily up the chain to find a scala dependency. so you have to define your scala dependency on all projects that apply the crossbuild plugin.

**Comment by borissmidt** [comment]
I've looked further in the code and i slowly get the feeling that it still is an easier solution to be able to tell the plugin to replace _2.11 or _2.12 or _2.13 or whatever with the scala version. So then the plugin doesn't need to edit the main sourceset at all.

**Pull request merged**
